# Dockerfile

# pull the official docker image
FROM python:3.11.1-slim

RUN apt-get update && apt-get install -y --no-install-recommends\
    build-essential \
    libpq-dev \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*  \
    libpq-dev

# set work directory
WORKDIR /app

# set env variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
COPY requirements.txt requirements-dev.txt ./
RUN pip install psycopg2
RUN pip install sqlparse
RUN pip install --upgrade pip
RUN pip install "pydantic[dotenv]"
RUN pip install -r requirements-dev.txt
RUN pip install watchfiles

# copy project
COPY app/ /app/
COPY requirements.txt requirements-dev.txt /app/
COPY alembic.ini /app/
COPY pytest.ini /app/
COPY setup.cfg /app/
COPY alembic /app/
COPY docker/docker-compose.yml /app/
COPY pylintrc /app/
COPY scripts /app/
COPY README.md  /app/

# copy entrypoint script
COPY docker/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
