FROM python:3.11.1-slim

RUN apt-get update && apt-get install -y --no-install-recommends\
    build-essential \
    libpq-dev \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*  \
    libpq-dev

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt requirements-dev.txt ./
RUN pip install psycopg2
RUN pip install sqlparse
RUN pip install --upgrade pip
RUN pip install "pydantic[dotenv]"
RUN pip install -r requirements-dev.txt
RUN pip install watchfiles

COPY app/ /app/
COPY requirements.txt requirements-dev.txt /app/
COPY alembic.ini /app/
COPY pytest.ini /app/
COPY setup.cfg /app/
COPY alembic /app/
COPY docker/docker-compose.yml /app/
COPY pylintrc /app/
COPY scripts /app/
COPY README.md  /app/

COPY docker/entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
